version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:9.6
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/data/postgres
    env_file:
      - .env
